# Generated by Django 3.2.19 on 2023-06-26 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0003_course_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
    ]
